TOPIK_DESCRIPTIONS = {
    1: "absolute beginner — knows Hangul basics, simple greetings, numbers",
    2: "beginner — ~800 vocab words, present/past tense, simple sentences",
    3: "intermediate — ~1500-2000 vocab, expressing opinions, compound sentences",
    4: "upper-intermediate — ~3000 vocab, news topics, abstract reasoning",
    5: "advanced — ~5000 vocab, formal/informal register, complex grammar",
    6: "master — near-native, nuanced usage, idiomatic expressions",
}

TOPIK_GRAMMAR_CURRICULUM = {
    1: [
        "이다/아니다 (to be / not to be)",
        "은/는 (topic marker)",
        "이/가 (subject marker)",
        "을/를 (object marker)",
        "에 (location/time particle)",
        "Present tense: -아/어요",
        "Past tense: -았/었어요",
        "Negation: 안 + verb",
        "있다/없다 (existence/possession)",
        "-(으)로 (direction/means)",
    ],
    2: [
        "-(으)ㄹ 거예요 (future tense)",
        "-고 싶다 (want to)",
        "못 + verb (can't)",
        "-(으)면 (if/when conditional)",
        "-(아/어)서 (because/so, sequential)",
        "-(으)ㄴ/는데 (background contrast)",
        "-지만 (but/however)",
        "-(으)ㄹ 수 있다/없다 (can/cannot)",
        "-기 전에 (before doing)",
        "-고 나서 (after doing)",
    ],
    3: [
        "-(으)ㄴ 후에 (after noun/verb)",
        "-는 동안 (while doing)",
        "-(으)ㄹ 때 (when/at the time of)",
        "-게 되다 (come to / end up doing)",
        "-아/어 보다 (try doing)",
        "-(으)ㄹ 것 같다 (seems like / I think)",
        "-든지 (regardless of / either or)",
        "-기 위해서 (in order to)",
        "passive voice: -이/히/리/기",
        "causative: -이/히/리/기/우/추",
    ],
    4: [
        "-(으)ㄹ 뿐만 아니라 (not only... but also)",
        "-에 따라 (depending on / according to)",
        "-(으)ㄹ수록 (the more... the more)",
        "-는 한 (as long as)",
        "-에도 불구하고 (despite / in spite of)",
        "indirect speech: -다고 하다",
        "-(으)ㄴ/는 반면에 (on the other hand)",
        "-아/어야 하다 (must / have to)",
        "Honorific speech level: -(으)십니다",
        "-(으)ㄹ 텐데 (I expect / should be)",
    ],
    5: [
        "-(으)ㄹ 법하다 (likely/plausible)",
        "-는 바람에 (because of/due to, negative)",
        "-(으)ㄴ/는 탓에 (because of, blame)",
        "-(으)ㄹ 지경이다 (to the point of)",
        "-고자 하다 (intend to / plan to)",
        "-(으)ㄴ/는 셈이다 (it amounts to / it is as if)",
        "-아/어도 (even if/though)",
        "-(으)ㄹ 만하다 (worth doing / bearable)",
        "Contracted speech patterns",
        "Formal vs informal register contrast",
    ],
    6: [
        "Literary/written language endings: -다, -ㄴ다",
        "Archaic/formal endings in official documents",
        "Proverbs and idiomatic four-character expressions (사자성어)",
        "Nuances of speech levels: 해요체 vs 합쇼체 vs 해체",
        "-(으)ㄹ 따름이다 (can only / nothing but)",
        "-(으)ㄹ진대 (given that / since — formal)",
        "Advanced nominalization with -음 vs -기",
        "-(으)로 인해 (due to — formal/written)",
        "Double subject constructions",
        "Complex relative clauses",
    ],
}

DAILY_CHALLENGE_SENTENCES = {
    1: [
        "I go to school every day.",
        "This is my bag.",
        "The weather is nice today.",
        "I like Korean food.",
        "Where is the bathroom?",
        "How much is this?",
        "I am a student.",
        "Please speak slowly.",
    ],
    2: [
        "I want to travel to Korea next year.",
        "Can you recommend a good restaurant?",
        "I have been studying Korean for six months.",
        "She called me because she was worried.",
        "I can't eat spicy food.",
        "Before going to sleep, I read a book.",
    ],
    3: [
        "The more I study, the more I realize how much I don't know.",
        "Despite being tired, he finished all his work.",
        "I ended up moving to a new city for work.",
        "While I was cooking, my friend came over.",
        "In order to improve my Korean, I practice every day.",
    ],
    4: [
        "Not only did she pass the exam, but she also got the highest score.",
        "Depending on the weather, we may cancel the outdoor event.",
        "As long as you keep practicing, you will definitely improve.",
    ],
    5: [
        "The government announced new policies aimed at reducing carbon emissions.",
        "Despite the difficulties, the team managed to complete the project on time.",
    ],
    6: [
        "The significance of cultural exchange cannot be overstated in today's globalized world.",
        "One must consider both the short-term benefits and long-term consequences of such decisions.",
    ],
}
